// https://scrapbox.io/nostr/%E4%B8%BB%E8%A6%81%E3%82%AF%E3%83%A9%E3%82%A4%E3%82%A2%E3%83%B3%E3%83%88%E3%81%AE%E3%83%87%E3%83%95%E3%82%A9%E3%83%AB%E3%83%88%E3%83%AA%E3%83%AC%E3%83%BC

export const CommonRelays = {
  NIP50SearchCapabilityCompatibles: [
    'wss://relay.nostr.band',
    'wss://search.nos.today',
    'wss://nostrja-kari-nip50.heguro.com',
    'wss://universe.nostrich.land',
    //`wss://filter.nostr.wine/REPLACE_WITH_YOUR_NPUB?broadcast=true`,
  ],
  MutinyWallet: ['wss://relay.mutinywallet.com'],
  Coracle: [
    // "wss://brb.io",
    'wss://nostr.zebedee.cloud',
    // "wss://nostr-pub.wellorder.net",
    'wss://relay.nostr.band',
    'wss://nostr.pleb.network',
    'wss://relay.nostrich.de',
    'wss://relay.damus.io',
  ],
  Iris: [
    'wss://eden.nostr.land',
    'wss://nostr.fmt.wiz.biz',
    'wss://relay.damus.io',
    // "wss://nostr-pub.wellorder.net",
    // "wss://relay.nostr.info",
    'wss://offchain.pub',
    'wss://nos.lol',
    // "wss://brb.io",
    'wss://relay.snort.social',
    'wss://relay.current.fyi',
    // "wss://nostr.relayer.se",
  ],
  DamusRelays: ['wss://relay.damus.io', 'wss://eden.nostr.land'],
  AmethystRelays: [
    'wss://nostr.bitcoiner.social',
    'wss://relay.nostr.bg',
    'wss://relay.snort.social',
    'wss://relay.damus.io',
    'wss://nostr.oxtr.dev',
    // "wss://nostr-pub.wellorder.net",
    'wss://nostr.mom',
    'wss://no.str.cr',
    'wss://nos.lol',
  ],
  JapaneseRelays: [
    'wss://relay.nostr.wirednet.jp',
    'wss://relay-jp.nostr.wirednet.jp',
    // "wss://ipv6.nostr.wirednet.jp",
    'wss://nostr.holybea.com',
    'wss://nostr.fediverse.jp',
    'wss://yabu.me',
    'wss://nostr-relay.nokotaro.com',
    'wss://nrelay.c-stellar.net',
    // "wss://nrelay-jp.c-stellar.ne",
    'wss://relay.yozora.world',
    'wss://r.kojira.io',
  ],
}
